# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('mail', models.CharField(max_length=60, verbose_name='mail')),
                ('asunto', models.CharField(max_length=100, verbose_name='asunto')),
                ('comentario', models.TextField()),
            ],
        ),
    ]
