# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-27 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Contacto',
        ),
    ]
