# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='materias',
            name='id',
        ),
        migrations.AlterField(
            model_name='materias',
            name='id_materia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
